apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: surrealdb-data
  labels:
    app.kubernetes.io/name: surrealdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: coe-netapp-san
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-notebook-data
  labels:
    app.kubernetes.io/name: open-notebook
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: coe-netapp-san
