apiVersion: v1
kind: Secret
metadata:
  name: opennotebook-secrets
  labels:
    app.kubernetes.io/name: open-notebook
type: Opaque
stringData:
  encryption-key: 0p3nN0t3b00k
  surreal-user: root
  surreal-password: root
